language: node_js
node_js:
  - "8"
cache:
  directories:
      - "node_modules"
install: npm install
before_script: npm run export
script: npm test
deploy:
  - provider: script
    script: npx now dist -A ../now.json --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
  - provider: script
    script:  npx now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      branch: master
