language: node_js
node_js:
  - "8"
install: npm install
script: npm run build && npm run build:rss && npm run dist
before_deploy: npm install now --no-save
deploy:
  provider: script
  script: npm run deploy && npm run alias
  skip_cleanup: true
  on:
    branch: master